backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
- name: "map_data"
    label: "بيانات الخريطة"
    folder: "data/map"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "المحافظة", name: "province", widget: "string"}
      - {label: "عدد الأشجار", name: "tree_count", widget: "number"}
      - {label: "الحالة", name: "status", widget: "select", options: ["تم الزراعة", "تحت المراقبة"]}
      - {label: "تاريخ الزراعة", name: "date", widget: "datetime"}
  - name: "blog"
    label: "المقالات"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
