backend:
  name: github
  repo: luxxpert/luxxpert.github.io # اسم حسابك/المستودع
  branch: main # أو master حسب الفرع الأساسي عندك
  base_url: https://api.github.com # هذا السطر يربطك مباشرة بـ GitHub

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
